version: '3.8'

services:
  mongo:
    extends:
      file: docker-compose-base.yml
      service: mongo
    deploy:
      resources:
        limits:
          memory: 1g
    labels:
      kompose.service.type: "LoadBalancer"

  mongodb-compass:
    extends:
      file: docker-compose-base.yml
      service: mongodb-compass
    deploy:
      resources:
        limits:
          memory: 500m
    labels:
      kompose.service.type: "LoadBalancer"

  streamlit:
    extends:
      file: docker-compose-base.yml
      service: streamlit
    deploy:
      resources:
        limits:
          memory: 500m
    labels:
      kompose.service.type: "LoadBalancer"

networks:
  ml-network:
    external: true
